places_to_visit = ["cabo san lucas", "belize", "egypt", "st. lucia", "negril"]
print("Places to visit: ", places_to_visit)
print("Places to visit sorted: ", sorted(places_to_visit))
print("Places to visit original order: ", places_to_visit)
print("Places to visit sorted: ", sorted(places_to_visit, reverse=True))
print("Places to visit original order: ", places_to_visit)
places_to_visit.reverse()
print("Places to visit reverse order: ", places_to_visit)
places_to_visit.reverse()
print("Places to visit original order: ", places_to_visit)
places_to_visit.sort()
print("Places to visit alphabetical order: ", places_to_visit)
places_to_visit.sort(reverse=True)
print("Places to visit reverse alphabetical order: ", places_to_visit)
